container:
  image: smartrent/terraform-ci:1.2.1
  cpu: 1

base: &base
  timeout_in: 30m

task:
  <<: *base
  name: terraform format
  format_script:
    - terraform fmt -check -recursive

task:
  <<: *base
  name: terraform validate
  validate_script:
    - terraform init -input=false -backend=false
    - terraform validate

task:
  <<: *base
  name: tflint
  tflint_script:
    - terraform init -input=false -backend=false
    - tflint --init --config .tflint.hcl
    - tflint --module --config .tflint.hcl

task:
  <<: *base
  name: tfsec
  tfsec_script:
    - terraform init -input=false -backend=false
    - tfsec
